name: Deploy abstract web page

on:
  push:
    branches: [ 'release' ]
  merge_group:
    branches: [ 'release' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Yarn
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 19.6.0
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: './dist'
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1